title: Ernee Kozyreff Filho
#description: Optimization and Data Science
theme: jekyll-theme-minimal
logo: /assets/images/profile_picture.png
#nav:
#  - text: Home
#    link: /
#  - text: Bio and Experience
#    link: /bio
#  - text: Projects Portfolio
#    link: /projects
#google_analytics:
