remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Minimal theme
logo: /assets/images/profile_picture.png
description: Minimal is a theme for GitHub Pages.
google_analytics:
