title: Ernee Kozyreff Filho
logo: /assets/images/profile_picture.png
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal
nav:
  - text: Home
    url: /
  - text: Bio
    url: /bio.md
  - text: Projects
    url: /projects.md
