title: Ernee Kozyreff Filho
description: Optimization and Data Science
theme: jekyll-theme-slate
#theme: jekyll-theme-cayman
#theme: jekyll-theme-tactile
#theme: jekyll-theme-minimal
#logo: /img/headshot.png
#google_analytics:
